global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'box-api'
    metrics_path: '/boxes/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8080']
    relabel_configs:
      - source_labels: [job]
        target_label: job
        replacement: 'boxes'
      - source_labels: [__name__]
        target_label: __name__
        regex: '(.+)'
        replacement: 'boxes.${1}'

  - job_name: 'user-api'
    metrics_path: '/accounts/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8080']
    relabel_configs:
      - source_labels: [job]
        target_label: job
        replacement: 'users'
      - source_labels: [__name__]
        target_label: __name__
        regex: '(.+)'
        replacement: 'users.${1}'

  - job_name: 'flat-api'
    metrics_path: '/flats/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8080']
    relabel_configs:
      - source_labels: [job]
        target_label: job
        replacement: 'flats'
      - source_labels: [__name__]
        target_label: __name__
        regex: '(.+)'
        replacement: 'flats.${1}'

  - job_name: 'postgres'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'keycloak'
    static_configs:
      - targets: ['keycloak:9000']
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [job]
        target_label: job
        replacement: 'keycloak'
      - source_labels: [__name__]
        target_label: __name__
        regex: '(.+)'
        replacement: 'keycloak.${1}'
