\c boxes
DO $$
BEGIN
   IF EXISTS (SELECT 1 FROM pg_available_extensions WHERE name = 'pg_cron') THEN
      CREATE EXTENSION IF NOT EXISTS pg_cron;
   END IF;
END $$;

GRANT USAGE ON SCHEMA cron TO box_user;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA cron TO box_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA cron GRANT EXECUTE ON FUNCTIONS TO box_user;

\c flats
CREATE EXTENSION cube;
CREATE EXTENSION earthdistance;
